name: learn-ci-docker
run-name: ${{github.actor}} is learning Github Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  install-makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - shell: bash
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install make

      - shell: bash
      - name: Build docker from make file
        run: make docker_build IMG=learn_docker_ci