name: test Go
run-name: ${{github.actor}} is learning github action

on:
  push:
    branches:
      - tester/*

jobs:
  test-golang:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install make

      - name: Hello World
        run: make run_hello_world

        
    
    
  




